### ISSUE TITLE
It simply does not work or i'm clueless

### ISSUE THREAD

**Issue by KorayAydemir** [Toqozz/wired-notify#108]
I installed it, copied someone else's config. The program does not open anything when its run. It it supposed to or am i missing a step ? Same result when i remove config file so it uses the default.

![2022-10-18-191913_956x1048_scrot](https://user-images.githubusercontent.com/54016693/196487072-e633e8d6-5edc-4c96-b4ec-90e1ec7cd47c.png)

**Comment by av-lukas** [comment]
Send screenshot of your setup, when done 😉

It's always nice to see new setups to I spire our own.

**Comment by pleshevskiy** [comment]
@KorayAydemir What file manager do you use?

**Comment by KorayAydemir** [comment]
I'm using "ranger" file manager.

This is my setup it's not so creative just mixup of several setups from r/unixporn

![2022-10-19-003027_1920x1080_scrot.png](https://user-images.githubusercontent.com/54016693/196648746-df35fdd8-8f96-42a0-aa3e-c0d191dc9b0d.png)
