### ISSUE TITLE
Error with recents versions.

### ISSUE THREAD

**Issue by AndresD172** [Toqozz/wired-notify#109]
Hello!

Recently, I compiled Wired to upgrade the old version I had installed in my PC. Wired compiled fine, but when I tried to run it the only message that I got in terminal is: 

"thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }', src/cli.rs:50:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace"

An then, Wired crashes.

Edit: Using sudo, Wired works. The problem only appear when I run Wired as a normal user. 

Sincerely,
Andrés.

**Comment by Toqozz** [comment]
Hmm.  It looks like it's having trouble removing the old socket, maybe it's owned by a different user or something?  Can you try manually remove /tmp/wired.sock?  (or reboot, which should do the same thing).
