### ISSUE TITLE
wired "panicked" when run as systemd --user unit

### ISSUE THREAD

**Issue by ChasNelson1990** [Toqozz/wired-notify#112]
I think I've read all the issue and PR threads on autorunning (and restarting) wired using systemd and have tried several permutations and keep getting the below issue.

I am currently using this form for wanted.service:

```
[Unit]
Description=Wired notification daemon
Documentation=https://github.com/Toqozz/wired-notify
PartOf=graphical-session.target

[Service]
Type=dbus
BusName=org.freedesktop.Notifications
ExecStart=/usr/bin/wired
Restart=always
RestartSec=10

[Install]
WantedBy=default.target
```

This is a mixture of the Dunst service, the discussion in #105 and the service file in the repo. This file seems to a) try to run wired after `startx` and b) tried to restart wanted when it fails.

Sadly, it always fails with:

```
systemd[3656]: Starting Wired notification daemon...
wired[266729]: A wired socket exists; taking ownership.  Existing wired processes will not receive CLI calls.
systemd[3656]: Started Wired notification daemon.
wired[266729]: Notification bus name acquired.
wired[266729]: thread 'main' panicked at 'Couldn't create an X11 event loop.: XOpenDisplayFailed', src/main.rs:101:47
wired[266729]: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
systemd[3656]: wired.service: Main process exited, code=exited, status=1/FAILURE
systemd[3656]: wired.service: Failed with result 'exit-code'.
```

And then restarts 10 seconds later.

This is true both for https://aur.archlinux.org/packages/wired and https://aur.archlinux.org/packages/wired-git (latest updates of each).

I am running Arch (kernel 6.1.1-arch1-1) and i3 (v4.21.1).

Any thoughts? Slash any extra info I can provide.

**Comment by Toqozz** [comment]
Hmm... these service files are really annoying.

Can I get a grab a few more pieces of info from you?:

1. Does wired start correctly when launched "manually"?
2. Does dunst launch fine using their provided service file?
3. Is wired able to start after the 10 second retry?

I think the answers will likely be...

1. yes
2. no (though, maybe timing could change this)
3. yes

In which case, it seems like wired is trying to start before X.  It really seems like we want `Requires=graphical-session.target` so that wired definitely starts *after* X.  But then looking over #105 again, it *seems* like maybe a reason for not having it after `graphical-session.target` is so that you can get notifications in login managers.  This is unconfirmed.

We probably need a Q/A sections with some different systemd services for different use-cases, if we want to properly support this stuff.

Can you try with `Requires=graphical-session.target` and see what the result is?  I'd like to know if that actually fixes it.

**Comment by ChasNelson1990** [comment]
Thanks for getting back to me :smile: 

1. Yes - but seems to fail after some time (I think possibly when I connect / disconnect to my dock (and thus additional monitors)?); this is my motivation for having something handle restarts
2. The one that comes installed with Arch Linux's AUR dunst-git package does not work, it fails because it is missing an [Install] section.
3. No. Wired tries to restart every 10 seconds but fails with exactly the same error. Also fails if I manually restart.


Tried wired.service with Requires but still fails with the same error.

**Comment by pleshevskiy** [comment]
I use the following configuration and it works as expected.

```
[Install]
WantedBy=graphical-session.target

[Service]
BusName=org.freedesktop.Notifications
ExecStart=/usr/bin/wired
Type=dbus

[Unit]
Description=Wired Notification Daemon
PartOf=graphical-session.target
```

Try to change `WantedBy=default.target` to `WantedBy=graphical-session.target` in Install section

**Comment by Toqozz** [comment]
> 1. Yes - but seems to fail after some time (I think possibly when I connect / disconnect to my dock (and thus additional monitors)?); this is my motivation for having something handle restarts

Interesting.  I should probably fix that.

> 3. No. Wired tries to restart every 10 seconds but fails with exactly the same error. Also fails if I manually restart.

That's weird, and makes me feel like it's not actually some kind of race with the targets and something else, but that error should only happen when trying to connect to an X server, so I dunno.

Can you try @pleshevskiy's config and see if that changes things?

**Comment by ChasNelson1990** [comment]
Nope, @pleshevskiy's config gives me the same error (but doesn't restart as it doesn't include those lines.

Is it important to note that I am starting i3 with an `exec` statement in a .xinitrc file that is being used when I manually run `startx` after logging in just through the tty? i.e. no graphical login manager or automated wm start?

**Comment by chicuongha** [comment]
I got same issue with river.
To solve the issue, you need to add Environment="DISPLAY=:0"

**Comment by jokeyrhyme** [comment]
If you put `ConditionEnvironment=DISPLAY` in the [Unit] section, it'll refuse to start until after the DISPLAY environment variable is available within whatever is starting `wired` (e.g. systemd user service manager, or dbus's activation environment)

**Comment by Toqozz** [comment]
I've added @jokeyrhyme's suggestion to the `wired.service` file.  I'm closing this for now, but feel free to keep discussing/reopen if there's more suggestions for how this service file actually should look.
