### ISSUE TITLE
Notification center

### ISSUE THREAD

**Issue by musjj** [Toqozz/wired-notify#114]
It would be nice if we can have a notification center:
![](https://extensions.gnome.org/extension-data/screenshots/screenshot_1526_xeYJZKO.png)

Or perhaps, a more general framework for creating our own notification center. 

We should be able to do things like filter what notifications we want to see in the panel. For example, we can choose to only display notifications that the user have not interacted with (by clicking it, closing it, etc.).

**Comment by av-lukas** [comment]
FYI You can make your own by inspecting logs and rendering wherever you see FIT. I have a premitive attempt at this using an Eww widget.

**Comment by lukelex** [comment]
FYI You can make your own by inspecting logs and rendering wherever you see FIT. I have a premitive attempt at this using an Eww widget.

**Comment by Toqozz** [comment]
Yeah, I'm sorry but this is out of scope for wired.  In the future with lua support you may be able to hack something together better, but it will never be a priority.  Sorry.
