### ISSUE TITLE
Nix-flakes: home-manager instructions still up to date?

### ISSUE THREAD

**Issue by TornaxO7** [Toqozz/wired-notify#115]
May I ask if the [Nix-flakes] chapter is still up to date? Because the [flake-output-scheme] doesn't provide `homeConfigurations` attribute.

[Nix-flakes]: https://github.com/Toqozz/wired-notify#nix-flakes
[flake-output-scheme]: https://nixos.wiki/wiki/Flakes#Output_schema

**Comment by Toqozz** [comment]
Hey, sorry, the Nix flakes are a community effort and I don't have much knowledge about it.  Perhaps @pleshevskiy can weigh in if they're still around.

**Comment by oddlama** [comment]
> May I ask if the [Nix-flakes](https://github.com/Toqozz/wired-notify#nix-flakes) chapter is still up to date? Because the [flake-output-scheme](https://nixos.wiki/wiki/Flakes#Output_schema) doesn't provide `homeConfigurations` attribute.

While this flake is using a slightly "non-standard" output attribute name (homeManagerModules vs hmModules) to expose the module, the chapter generally seems to be up to date to me. I'm using it without problems on my setup. There's a slight mistake though where the overlay is added:

```nix
pkgs = import nixpkgs {
  inherit system;
  overlays = [ wired.overlays.${system} ];
};
```

should be

```nix
pkgs = import nixpkgs {
  inherit system;
  overlays = [ wired.overlays.default ];
};
```

**Comment by TornaxO7** [comment]
thank you for the answer!

**Comment by TornaxO7** [comment]
Hm... would you think that it's worth it to create a PR to `home-manager` for this?
