### ISSUE TITLE
`idle_poll_interval` doesn't seem to do anything

### ISSUE THREAD

**Issue by YanDoroshenko** [Toqozz/wired-notify#117]
What it says on the tin - `idle_poll_interval` doesn't seem to do anything. There's no noticeable difference between 1 and 1000000.

**Comment by Toqozz** [comment]
That option is used when no windows are present.  A higher value should increase the delay between a notification being sent and the server displaying it.  I'm fairly sure it works, but I can take a look.

**Comment by Toqozz** [comment]
It looks like it doesn't get updated when the config is reloaded though, maybe that's what you're seeing.  I'll fix that.

**Comment by Novaryu** [comment]
Not sure if OP is using `master`, but I did notice when building wired from the AUR it didn't have `idle_poll_interval` in the src (config.rs) and thus changing the setting did nothing. However, wired-git (master) did and building that allowed the setting to be changed. It even updates when the config is reloaded from what I've tested.

**Comment by YanDoroshenko** [comment]
@Novaryu That seemed to indeed be the culprit. Installed `wired-git` and everything is fine now. Thanks!
