### ISSUE TITLE
[Request] Hold notifications while screen is off

### ISSUE THREAD

**Issue by LordMZTE** [Toqozz/wired-notify#12]
It would make it easier to see missed notifications if wired would not show them while the screen is turned off (which happens after some time without input by default), and then show them once the screen turns back on so it's easier to catch up on missed notifications.

**Comment by Toqozz** [comment]
Basic support for this available in 83c4c28, forgot to tag the issue.

After being idle for longer than `idle_threshold`, Wired will pause any existing and new notifications (same as using the `notification_pause` shortcut).  When you come back from being idle, the paused notifications will remain paused and need to be cleared manually, but new notifications will of course behave normally.

The other option I see is just unpausing everything when you get back from idle, but there's annoying things like overriding notifications that have been manually paused.

We could also just pause the whole daemon when idle and process events when the user gets back, but I don't like that either.

**Comment by Toqozz** [comment]
Available in [0.9.3](https://github.com/Toqozz/wired-notify/releases/tag/0.9.3).
