### ISSUE TITLE
Version number of `0.10.3` is incorrect

### ISSUE THREAD

**Issue by xrelkd** [Toqozz/wired-notify#126]
Steps to reproduce:
1. Download https://github.com/Toqozz/wired-notify/archive/refs/tags/0.10.3.tar.gz
2. Extract the tarball and change directory to `wired-notify`
3. Build and run `wired` with the following commands:
```bash
cargo build --release
./target/release/wired --version
```
`wired` shows 
```
0.10.2
```
instead of
```
0.10.3
```

Please bump the version number of https://github.com/Toqozz/wired-notify/blob/0.10.3/Cargo.toml to `0.10.3` and then update `Cargo.lock`.

**Comment by Toqozz** [comment]
Ahhh I missed that, damn.

Will fix shortly.

Thanks!

**Comment by Toqozz** [comment]
Should be good now.
