### ISSUE TITLE
Doesn't find URL

### ISSUE THREAD

**Issue by nazar-pc** [Toqozz/wired-notify#144]
Just compiled from 19b8896f6d89321531c78ef5c2575963501e1a65 and notifications from Firefox when clicked are not opening Firefox tab with this printed in logs:
> Was requested to open a url but couldn't find one in the specified string

**Comment by Toqozz** [comment]
What does the notification string look like?

**Comment by nazar-pc** [comment]
Here is Slack notification for example:
```
method call time=1714882726.475586 sender=:1.44 -> destination=:1.22 serial=326 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "Nightly"
   uint32 0
   string ""
   string "New message from Slackbot"
   string "What do you know, it works?"
   array [
      string "default"
      string "Activate"
   ]
   array [
      dict entry(
         string "desktop-entry"
         variant             string "Firefox"
      )
      dict entry(
         string "suppress-sound"
         variant             boolean false
      )
      dict entry(
         string "sender-pid"
         variant             int64 9962
      )
   ]
   int32 -1
```

**Comment by nazar-pc** [comment]
No sure, I didn't work with this kind of stuff before, but I guess `sender-pid` is what might be somehow used for sending a signal back?

**Comment by Toqozz** [comment]
Right, I think I understand what you're saying now.

To open firefox from the notification, firefox will need to define some actions -- it seems like it does define a default action to activate the window.

You'll need to add a `ButtonBlock` to your config to be able to use these.  Take a look at https://github.com/Toqozz/wired-notify/wiki/ButtonBlock for the documentation, or [have a look at some configs others have done.](https://github.com/Toqozz/wired-notify/issues/63).

**Comment by nazar-pc** [comment]
Hm... looks like what I wanted is to not add button block, but rather assign `notification_action1` to 1 instead of `notification_interact`. Not sure what "Interacts with a block within a notification" means, but apparently it wasn't what I needed.
