### ISSUE TITLE
Replacement doesn't reset hide timeout

### ISSUE THREAD

**Issue by nazar-pc** [Toqozz/wired-notify#146]
When replacement happens from music player with a different track, original hide timeout is still ticking, so after switching a few tracks in a row notification disappears, while expectation was that notification would hide some time after last replacement instead.

**Comment by Toqozz** [comment]
We can have this as an option for sure, thanks!  Will get to that soon.

**Comment by Toqozz** [comment]
Oh, we actually already have an option for this: `replacing_resets_timeout`.

https://github.com/Toqozz/wired-notify/blob/8ecd477c0ef921bc0abb8f7df823dda1cd78960e/wired.ron#L51

**Comment by nazar-pc** [comment]
Indeed, not sure how I missed it. Now wondering who wouldn't want it :thinking:
