### ISSUE TITLE
Rounded Borders

### ISSUE THREAD

**Issue by cecilialau6776** [Toqozz/wired-notify#152]
It seems that that `border_rounding` property on `NotificationBlock`s only rounds the inside, and not the outside. I'd love for both to be rounded but for now, a workarounds might be to set the `border_rounding` property, show no border, use the `NotificationBlock` as a 'border' and have an inner `NotificationBlock` that that actually has the content you want.

**Comment by Toqozz** [comment]
This is by design.  If we round the outer borders there is no way for us to make the compositor understand, and so the compositor shadows will still be on the pointy corners.

Rounded outer corners should be done at the compositor level.  For Picom this is the `corner-radius` option.
