### ISSUE TITLE
Suggestion for implementing keyboard shortcuts

### ISSUE THREAD

**Issue by BlueDrink9** [Toqozz/wired-notify#18]
Instead of writing a whole keyboard shortcut system yourself, here is a simpler alternative:
Expose an api, possibly via dbus or a named pipe or a socket, such that you could run `$ wired_c notification_close`. Then, anyone who wants keyboard shortcuts could set them up via their window manager, or via Autokey or sxhkd or some other prefered keyboard shortcut manager.

**Comment by Toqozz** [comment]
See #6!
