### ISSUE TITLE
Display and handle notification actions

### ISSUE THREAD

**Issue by cubetastic33** [Toqozz/wired-notify#2]
There should be a way to handle the notification's actions, for example I should be able to set it such that right clicking a notif executes the default action. There should also be a way to see all the actions in the notification. For example, discord notifications come with an action of going to that chat - so if I've configured my right mouse click to the default action, right clicking a discord notification should take me to that chat.

**Comment by Toqozz** [comment]
Hmm.  This sounds like a good idea.

Are you at all familiar with how the `actions` parameter works?  I haven't used it before and the specifications are a bit vague.

**Comment by cubetastic33** [comment]
I'm not familiar with the low level stuff, but [here](https://github.com/dunst-project/dunst/issues/234)'s a relevant issue in the dunst repo. Something like this would be ideal:
![screenshot](https://3.bp.blogspot.com/-vfPYETQBckQ/UiOXdAZYQdI/AAAAAAAAKnM/x1MdKs3ygBw/s1600/nuvola3.png)

With dunst, you can set it up such that clicking the notification executes the action if there's only one, and if there are multiple then it shows them using dmenu. Something like that would be fine as well. Some examples of apps that have actions in their notifs are discord and blueman (bluetooth client).

**Comment by cowlingj** [comment]
From my understanding, #848 should just about do what you're describing, i.e. clicking the configured mouse button will open the context menu, displaying the available actions. Does that sound like what you're after?

**Comment by Toqozz** [comment]
Working on this a bit.

My first thoughts were to just add a new action to `ShortcutsConfig` for each action -- `action1`, `action2`, `action3`, etc.  Problem is there's no particular ordering for actions, so there wouldn't be any real consistency across notifications.  There is a "default" action which is supposed to always be present, which should handle most cases though.

It shouldn't be too difficult to create a `Button` block from there that people can put in their configs.  Maybe something like a `ButtonGroup` which just shows all the actions could be good too.

Anyway, just documenting thoughts.  LMK if you have any input on that.

**Comment by cubetastic33** [comment]
I think there should be an option for a shortcut to fire the default action, and the block for multiple actions sounds good.

**Comment by Toqozz** [comment]
Partial (untested) implementation in 71a00a7 (dev branch).

In `ShortcutsConfig`, you can assign shortcuts for `notification_action1/2/3/4`, where 1 is the default action, and 2/3/4 are any other actions in arbitrary order.
https://github.com/Toqozz/wired-notify/blob/71a00a789857a1aa289b2df9026c8511961889b7/wired.ron#L87-L97

Ill merge this into master after I've tested it more and added a few more things, but if you wanted to try it now it's there.

Eventually I'll get round to buttons but it'll probably be a little while.

**Comment by Toqozz** [comment]
We've got buttons and shortcuts in the `0.9.0` release: https://github.com/Toqozz/wired-notify/releases/tag/0.9.0

Please give it a try and let me know/re-open if anything is bad.

Closing for now.
