### ISSUE TITLE
[Feature request] Tag-based notification replacement

### ISSUE THREAD

**Issue by GoldsteinE** [Toqozz/wired-notify#25]
dunst supports `string:x-dunst-stack-tag:<tag>` hint, which allows both replacing notifications using unpatched notify-send and doing so without having to remember ID on the side of a script. Similar feature would in wired would be very useful for sending notifications from scripts.

**Comment by Toqozz** [comment]
This is now available on master.

Use it like:
```sh
notify-send "Summary" "Body" --hint="string:wired-tag:tag_name"
notify-send "Summary" "A different body" --hint="string:wired-tag:tag_name"
```

**Comment by GoldsteinE** [comment]
Thanks!
