### ISSUE TITLE
Reliably vertically and horizontally center NotificationBlock on screen

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#27]
Would you entertain an easy way to center notifications on any screen size?

```rust
(
 name: "root",
 hook: Hook(parent_hook: MM, self_hook: MM), // MM = Middle Middle? Or, BM = Bottom Middle?
 offset: Vec2(x: 0, y: 150),
 params: NotificationBlock(( ... )),
 ...
)
```

Ultimately I'm interested in making notifications such as the following volume display:
![image](https://user-images.githubusercontent.com/842850/140776970-f55ebeba-d7ee-4982-b73e-ccabaf780a11.png)

**Comment by Toqozz** [comment]
Good idea!  I'll have a look into this.

**Comment by Toqozz** [comment]
Available in master.  Please let me know if you have any issues with it!
