### ISSUE TITLE
Notifications are cropping by the first one

### ISSUE THREAD

**Issue by PoSayDone** [Toqozz/wired-notify#3]
Hi! If I set hook to "TR" value, very long notifications are cropping by the length of the first one.
![image](https://user-images.githubusercontent.com/29358657/116974807-16c73700-acd8-11eb-8deb-ae1f5b7dfcda.png)

**Comment by Toqozz** [comment]
Hey, thanks for the issue!

What value are you using for `notification_hook` inside your `NotificationBlock` ([doc here](https://github.com/Toqozz/wired-notify/wiki/NotificationBlock)?

If you're using `notification_hook: Hook(parent_anchor: BL, self_anchor: TL)` like in the default config, then this behaviour is expected.  Try using `notification_hook: Hook(parent_anchor: BR, self_anchor: TR)` instead.

I'm not at my computer for a while so if that doesn't work or if you're already doing that, then I'll look into it when I get back :).

**Comment by PoSayDone** [comment]
> Hey, thanks for the issue!
> 
> What value are you using for `notification_hook` inside your `NotificationBlock` ([doc here](https://github.com/Toqozz/wired-notify/wiki/NotificationBlock))?
> 
> If you're using `notification_hook: Hook(parent_anchor: BL, self_anchor: TL)` like in the default config, then this behaviour is expected. Try using `notification_hook: Hook(parent_anchor: BR, self_anchor: TR)` instead.
> 
> I'm not at my computer for a while so if that doesn't work or if you're already doing that, then I'll look into it when I get back :).

That helped! Thanks!
