### ISSUE TITLE
Multiple styles of notifications

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#31]
Is there a way to have different styles of notifications running concurrently?
Maybe using hints?

`string:wired-name:centered`:
```ron
(
  name: "centered",
  params: NotificationBlock(( ... ))
)
```

`string:wired-style:top-right`:
```ron
(
  name: "top-right",
  params: NotificationBlock(( ... ))
)

**Comment by Toqozz** [comment]
This is an interesting idea.  Maybe it can be worked into [`render_criteria`](https://github.com/Toqozz/wired-notify/wiki/Blocks#render-criteria).  I will look into it.

**Comment by lukelex** [comment]
Here's an example of what I've been trying to accomplish.

https://gist.github.com/lukelex/d6fb76294ca48787169e21bb7f7d921e

The only thing missing is being able to position each type of notification independently.

**Comment by Toqozz** [comment]
I'm thinking the best way to enable this is probably by allowing multiple root blocks, and spawning a window for each of them that should draw.  It does clutter a few things for a smallish use case but seems intuitive.

**Comment by Toqozz** [comment]
I've just pushed a commit to master that allows for this.  It was a pretty big undertaking and I'm expecting it to be buggy, so please try it out!

**Comment by av-lukas** [comment]
Thanks for closing it. It works as I needed to, for now.

Completely forgot to follow up on this 😅
