### ISSUE TITLE
Weird clipping issue

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#32]
Depending on which window I'm focusing on, this clipping happens. I see it more often while focused and scrolling through my terminal.

https://user-images.githubusercontent.com/842850/143053053-316b16d2-ac81-4b90-a167-98582a0586fa.mov

**Comment by Toqozz** [comment]
What WM are you using?

**Comment by lukelex** [comment]
i3wm 4.20.1
Kernel 5.14.18-1-MANJARO
Wired 0.9.4-1

**Comment by Toqozz** [comment]
I can't seem to reproduce this on `i3wm 4.20.1` or in bspwm:

https://user-images.githubusercontent.com/6947819/143327003-c6baa9d9-986f-4bb2-b68e-657be84ff62f.mov

I'm using basically stock i3wm and picom with the following (maybe) relevant settings:
```
mark-wmwin-focused = true;
mark-ovredir-focused = false;
detect-rounded-corners = false;
unredir-if-possible = true;
refresh-rate = 0;
vsync = false;
```

Perhaps send over your wired config and I'll try that directly?  Also I see you have gaps -- are you using i3-gaps or is there a way to do gaps with vanilla i3?

**Comment by lukelex** [comment]
Here are the packages that might be useful to reproducing it:
**i3-gaps** | 4.20.1-1 | [config](https://github.com/lukelex/dotfiles/blob/wired/linux/config/i3)
**Wired** | 0.9.4-1 | [config](https://github.com/lukelex/dotfiles/blob/wired/linux/config/wired.ron)
**Picom** | 8.2-1 | [config](https://github.com/lukelex/dotfiles/blob/wired/linux/config/picom.conf)
**Kitty** | 0.23.1-1 | [config](https://github.com/lukelex/dotfiles/blob/wired/linux/config/kitty.conf)
**Polybar** | 3.5.5 | [config](https://github.com/lukelex/dotfiles/blob/wired/linux/config/polybar/bars.ini)
**Kernel** | Kernel 5.14.18-1-MANJARO

I've dug a tiny bit more and found out that I can reproduce the clipping by trigerring the notification from polybar's [volume](https://github.com/lukelex/dotfiles/blob/wired/linux/scripts/volume) module but when running the script mannually it works flawlessly. So maybe there's some weird behavior with how Polybar & Wired a playing together.

https://user-images.githubusercontent.com/842850/143440731-3d904f1b-9759-4c05-8339-63256bf127c2.mov

**Comment by lukelex** [comment]
- [ ]

**Comment by Toqozz** [comment]
Thanks for all the info!  So weird!

Will keep looking into this soon.

**Comment by Toqozz** [comment]
Ah man.  I've basically duplicated your setup and I still cannot reproduce this issue.

Same Wired/Picom/Polybar config, using Kitty, Kernel 5.15.4-arch1-1:

https://user-images.githubusercontent.com/6947819/143726593-199a5305-55e8-4344-8838-e1d92e9d9c3e.mp4

For reference, I'm using `nvidia 495.44-12`.

 My best guess at this point is that there's a weird graphics interaction or something with X11 is misbehaving.  I don't think this is an issue in Wired, but it could be in the windowing library we're using.  I'm still interested in trying to solve it, but it's difficult to move forward.

The works-when-script-run-separately-but-not-with-polybar especially makes me think something super weird is going on.  I had a brief look into polybar's [script run stuff](https://github.com/polybar/polybar/blob/abd96eb089d08eb2eefa4264f87978d6efbd772a/src/modules/script.cpp) but couldn't see anything that would make this happen.

Also, consider the [`replacing_resets_timeout`](https://github.com/Toqozz/wired-notify/wiki/Config) option which might make those volume controls a little more pleasant :).

**Comment by lukelex** [comment]
Given I can't provide a reproducible setup, lets close this one.
