### ISSUE TITLE
Can't figure out how to properly move notifications to the right corner

### ISSUE THREAD

**Issue by h5vx** [Toqozz/wired-notify#33]
While trying to move notifications to top-right corner, I end up with this config

```rust
// ...
    min_window_width: 400,
    layout_blocks: [
        (
            name: "root",
            parent: "",
            hook: Hook(parent_anchor: TR, self_anchor: TR),
            offset: Vec2(x: -7.0, y: 30.0),
            // https://github.com/Toqozz/wired-notify/wiki/NotificationBlock
            params: NotificationBlock((
                monitor: 0,
                border_width: 1.0,
                border_rounding: 0.0,
                //background_color: Color(r: 0.15686, g: 0.15686, b: 0.15686, a: 1.0),
                background_color: Color(hex: "#0C0E15"),
                border_color: Color(hex: "#282828"),
                border_color_low: Color(hex: "#282828"),
                border_color_critical: Color(hex: "#fb4934"),
                border_color_paused: Color(hex: "#fabd2f"),

                gap: Vec2(x: 0.0, y: 8.0),
                notification_hook: Hook(parent_anchor: BL, self_anchor: TL),
            )),
        ),
// ...
```

It's okay, but now longer notifications renders outside of screen, while there is shorter notifications above
![image](https://user-images.githubusercontent.com/47631174/143689110-73b4c1bc-4829-4f9a-90de-eef49899b85d.png)

And shorter notifications appears aligned to right side of longer notification
![image](https://user-images.githubusercontent.com/47631174/143689135-9a0d2432-af57-40bb-a828-b66d840fc584.png)

So how I configure anchors to achieve optimal behaviour?

**Comment by Toqozz** [comment]
Yeah, this seems to be a common issue.  See #3 .

Basically, you need to change `notification_hook` to hook correctly (probably `BR, TR` in your case).
