### ISSUE TITLE
Idle CPU usage to high

### ISSUE THREAD

**Issue by VuiMuich** [Toqozz/wired-notify#35]
I noticed that in idle while waiting for incoming notifications the COU usage sits relatively constant around 5% or slightly above.
Do you experience this as well?
Other daemons like my hotkey daemon typically use about 0.5% while listening for events.

**Comment by Toqozz** [comment]
Yeah, I have thought about this but been lazy about resolving it.

This is probably because Wired basically runs the entire main loop at `poll_interval`.

By default this value is pretty high, but there's also a lot of unnecessary work being done.

The primary solution here is to just not check nearly as often when there are no notifications being drawn.  I will try to be less lazy about fixing it now that you've brought it up.

**Comment by VuiMuich** [comment]
Just briefly had a look a your `main.rs` and an idea for a quick fix might be to try having a `idle poll_interval` of maybe 500ms and only bump to high speed during events and while the notifications is showing.

The more 'correct' solution would probably be to drastically lean the main loop and wait for events in an `async` listener. but this might result in a lot of work.

**Comment by Toqozz** [comment]
Yeah, I've actually implemented something similar this morning, but found that for some weird reason dbus seems to process `image-data` hints more slowly if `poll_interval` is higher.  You can probably see this in the current version even by just adjusting `poll_interval` and playing something on Spotify.  `100 ms` takes around ~6 seconds to show the notification, `1000 ms` about a minute, etc.  So weird.

I could be totally wrong that it's dbus causing this, but I don't see anything else that would do something like that.

Anyway, yeah so I got sidetracked updating dbus which has a lot of breaking changes.

**Comment by VuiMuich** [comment]
> `100 ms` takes around ~6 seconds to show the notification, `1000 ms` about a minute, etc. So weird.

This looks suspiciously linear.
Is there possibly a feedback loop hidden somewhere? This then could also be the source for the 'high' cpu load.

I see, why you would want to avoid the hassle of `async`. I just thought such a listener is kind of the textbook example.

**Comment by Toqozz** [comment]
I've implemented a fix for this in master.  We basically just poll every 500ms when there's no notifications, and at `poll_interval` when there is.  I considered having separate `draw_interval` and `poll_interval`s but I don't think it's worth the hassle and I doubt the vast majority of users want to tweak that value.

Also note that this is using kind of a workaround of just reading in dbus messages as they're received in a different thread and then sending them back to the main thread.  I think this is a good solution but I'm unsure if it's safe/guaranteed not to panic, even though it's only accessing by ref.  See https://github.com/diwic/dbus-rs/issues/364.
