### ISSUE TITLE
Dimensions#width->max is ignored

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#39]
# Description
Max width of a TextBox seems to be ignored whenever the text doesn't have spaces and max height is also provided.

```bash
notify-send 'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv' 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'
```

![image](https://user-images.githubusercontent.com/842850/146599504-3f4c15a8-8f77-40f4-a900-bf0a203bd70d.png)

## Config
        (
            name: "summary",
            parent: "root",
            hook: Hook(parent_anchor: BL, self_anchor: BL),
            offset: Vec2(x: 0.0, y: 0.0),
            // https://github.com/Toqozz/wired-notify/wiki/TextBlock
            params: TextBlock((
                    text: "%s",
                    font: "Arial Bold 16",
                    ellipsize: End,
                    color: Color(hex: "#ffffff"),
                    padding: Padding(left: 0.0, right: 0.0, top: 0.0, bottom: 0.0),
                    dimensions: (width: (min: -1, max: 500), height: (min: 100, max: 100)),
            )),
        ),

        (
            name: "body",
            parent: "summary",
            hook: Hook(parent_anchor: BL, self_anchor: BL),
            offset: Vec2(x: 0.0, y: 0.0),
            // https://github.com/Toqozz/wired-notify/wiki/ScrollingTextBlock
            params: TextBlock((
                    text: "%b",
                    font: "Arial 14",
                    ellipsize: End,
                    color: Color(hex: "#ffffff"),
                    padding: Padding(left: 0, right: 0, top: 0, bottom: 0),
                    dimensions: (width: (min: -1, max: 500), height: (min: 0, max: 0)),
                    scroll_speed: 0.1,
                    lhs_dist: 35.0,
                    rhs_dist: 35.0,
                    scroll_t: 1.0,
            )),
        ),

**Comment by Toqozz** [comment]
This seems to be caused by some default behaviour in [Pango](https://docs.gtk.org/Pango/method.Layout.set_wrap.html) which sets layouts to only wrap on word boundaries.  Wrapping isn't a factor on single line blocks (`height = 0`), which is probably why you don't see the same behaviour when `height` is `0`.

I've changed the default in Wired to `WrapWordChar`, which does the following:
> Wrap lines at word boundaries, but fall back to   character boundaries if there is not enough space for a full word.

It also hyphenates the word upon breaking it at a character boundary.
