### ISSUE TITLE
Allow using hint values in TextBlock

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#40]
I'd like to be able to refer to hint values inside TextBlock#text property.

```ron
TextBlock(text: "%p")
```

Example use case, display the progress value alongside the progress bar.

**Comment by Toqozz** [comment]
This should be pretty easy to add.  The only issue here is that percentage is represented internally as an `f32` between `0` and `1`, where `1` is 100% and `0` is 0%.

It's probably fine if we just make an assumption that the user wants the percentage in whole numbers between 0 and 100.

**Comment by Toqozz** [comment]
Available in master.
