### ISSUE TITLE
Percent-escapes being displayed literally

### ISSUE THREAD

**Issue by LordMZTE** [Toqozz/wired-notify#43]
I'm not quite sure what caused this, but I just recently updated wired, and now all my notifications are broken:
![image](https://user-images.githubusercontent.com/28735087/146955461-d98d5783-f854-4779-9468-b4d637b369b0.png)

It seems like the escape codes in the config aren't recognized anymore.

My config is available [here](https://mzte.de/git/LordMZTE/dotfiles/src/branch/master/.config/wired/wired.ron). I had a look at the docs, but couldn't find anything that's changed. I'm not sure if this is a bug or not.

**Comment by Toqozz** [comment]
Looks like I accidentally cut an extra line when moving some code around:

https://github.com/Toqozz/wired-notify/blob/89bcfa66ad4165369b648b53b2ff040d11a8162f/src/maths_utility.rs#L422-L451

Sorry about that.
