### ISSUE TITLE
`anti_render_criteria` doesn't seem to work

### ISSUE THREAD

**Issue by VerdeQuar** [Toqozz/wired-notify#46]
https://i.imgur.com/QVIPaBX.gif
![QVIPaBX](https://user-images.githubusercontent.com/35724192/148090996-04fe986f-ab39-4cfc-bb34-bd2e2521f183.gif)

I'm using `wired-git` with latest `wired.ron` from `master`, the only thing I changed is that I added offset to `root` block to be next to the image one
If I don't do that they just appear on top of each other
The same thing happens with discord so it's not problem with application sending the notification
Also, if text notifications (from layout 2) are replacing the old ones then I think the same should be true for the image ones (layout 1)

**Comment by VerdeQuar** [comment]
I don't know how but it sometimes randomlly switches and image notifications are replacing each other and text notifications are stacking

**Comment by Toqozz** [comment]
Thanks for the issue.

Sorry about that, fixed now.
