### ISSUE TITLE
Templating inside content

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#48]
Screenshot from Telegram's desktop app:
![image](https://user-images.githubusercontent.com/842850/148416225-1a5a7f22-7dc6-481d-bc26-ffe89d7151c3.png)

Should Wired be able to handle content that contains templating?

**Comment by Toqozz** [comment]
Wired does not (currently) support markup within notifications.  This kind of markup is something that I want to support eventually and we already do support pango markup in text fields: https://github.com/Toqozz/wired-notify/wiki/Text-Markup#pango-markup

I've removed the markup capability from the notification server, which should stop Telegram from sending us markup (if they check the capability...)
