### ISSUE TITLE
Feature: SVG Support

### ISSUE THREAD

**Issue by BeyondMagic** [Toqozz/wired-notify#53]
I know SVG isn't easy to play with, but many notification servers have it, so I'm just asking.

---

Pretty innovative idea though, thank you very much for it.

**Comment by lukelex** [comment]
+1

I've exported the entire FontAwesome library exported as png in order to have them work with Wired but not without it quirks.

**Comment by Toqozz** [comment]
Where do you want support for it?  If in image block, do some apps send notification hint images or app images as SVG?

**Comment by BeyondMagic** [comment]
> Where do you want support for it?

Image blocks.

> do some apps send notification hint images or app images as SVG?

Hard to tell, if there's a way to verify this, I'd help, but I can guess that no. Telegram, for example, caches the images as JPG, and then sends to the server with the hint images along the new message.

Not sure exactly the reasoning behind the question though, is it about recognizing the image being sent as SVG or (PNG, JPG, ...)? I thought many image-rendering libraries already had this 'built-in'.

**Comment by Toqozz** [comment]
> Not sure exactly the reasoning behind the question though

I'm trying to understand the use-case.  If all notify clients send PNGs, why do we need SVG support?  Just now I'm remembering that users can manually send images, which is probably the use case.

> I thought many image-rendering libraries already had this 'built-in'.

Unfortunately [`image-rs](https://github.com/image-rs/image) does not (which is surprising because it's massive!!!).  I'd have to pull in another library, all of which seem non-trivial.  Will keep looking at options though.

**Comment by BeyondMagic** [comment]
> I'm trying to understand the use-case. If all notify clients send PNGs, why do we need SVG support?

My bad, I should've made it clear before. I mostly use notification servers for Shell scripts, it's easier to automate certain processes, such as: recording with a keybind, and display a notification with a timer until it begins. I have a lot, really a lot, of those, and I think many people who uses Linux for *ricing* and making things easier for them send those notifications directly from scripts as well. The icons, in those cases, would help differentiating them.

---

Could I ask though if the `--icon` option shouldn't read it as an `image-path` as well?

```zsh
# Instead of only this:
notify-call --hint string:image-path:"$icons/definition.svg" "Love" "Means ..."
# Read as well:
notify-call --icon "$icons/definition.svg" "Love" "Means ..."

```

**Comment by Toqozz** [comment]
We *should* be handling this case.  IIRC we handle the `--icon` param as an "App" image, and the other ones as "Hint" images, which is adjusted in the `ImageBlock` settings.

https://github.com/Toqozz/wired-notify/blob/52dd38c93fceca54c0ecf47ec5c63476577be873/src/bus/dbus.rs#L364

My guess is that it's just not loading the SVG, but should handle that icon param fine.

**Comment by Toqozz** [comment]
SVG support has been added in master.  Naturally it only works when loading images from a path (e.g. `notify-send -i /home/user/img/ferris.svg "summary" "body"`).

Let me know if you run into any issues.

**Comment by lukelex** [comment]
> @lukelex Do you mean you would want to be able to specify that we just present the image as-is without any scaling? So e.g. set scale_width/scale_height to -1 for no scaling on that dimension?

Exactly. It's often the case that opposing images aren't the same size. (e.g. Volume & Mute)
![volume-svg](https://user-images.githubusercontent.com/842850/180739489-95189215-e434-461f-bb79-1f2ba5d63904.gif)
