### ISSUE TITLE
Notifications spawn in the top left of the screen

### ISSUE THREAD

**Issue by Sonic803** [Toqozz/wired-notify#71]
Even if they go on the right, for the first frame the notification spawns on the top left

**Comment by Toqozz** [comment]
Would you be able to drop your config file here?

**Comment by Sonic803** [comment]
[https://pastebin.com/U1MdP941](url)

**Comment by Toqozz** [comment]
I couldn't reproduce this locally, but can see why it might happen.  Would you mind trying the latest master version and telling me if it still happens?

**Comment by Sonic803** [comment]
Downloading the latest version and compiling it solved the issue, thanks a lot.
