### ISSUE TITLE
Progress render_criteria causing invalid config.

### ISSUE THREAD

**Issue by LordMZTE** [Toqozz/wired-notify#73]
# The bug
I have this block in my config:
```ron
    (
        name: "progress",
        parent: "body",
        hook: Hook(parent_anchor: BR, self_anchor: TR),
        offset: Vec2(x: 0.0, y: 0.0),
        render_criteria: [Progress],
        params: ProgressBlock((
            background_color: Color(hex: "#00000000"),
            border_color: Color(hex: "#ff79c6"),
            border_rounding: 0.0,
            border_width: 0.4,
            fill_color: Color(hex: "#ffb86c"),
            fill_rounding: 0.0,
            height: 10.0,
            padding: Padding(left: 8.0, right: 8.0, top: 0.0, bottom: 8.0),
            width: 500.0,
        )),
    ),
```
It uses the `Progress` `render_criteria` and results in this error when starting wired:
```
Found a config file: /home/lordmzte/.config/wired/wired.ron, but couldn't load it, so will use default one for now.
If you fix the error the config will be reloaded automatically.
        Error: Problem with config file: unknown variant `Progress`, expected `And` or `Or`
```
I'm not sure if this is a bug or an undocumented config change. My full config is available [here](https://mzte.de/git/LordMZTE/dotfiles/src/commit/0bb5bcffe733bf809ec7d59075a9519d668ba6f1/.config/wired/wired.ron) in case the error is actually somewhere else.

This used to work perfectly fine before the last wired update.

# Version Information
wired version: commit 720e24d
OS: Arch Linux, 5.17.7 kernel
WM: i3

**Comment by Toqozz** [comment]
Yeah!  This is expected.  I pushed some breaking changes and haven't really decided what I'm going to/how I'm going to do backwards compatibility.  Master isn't stable!

Having said that, I'll try to be more conscious of breaking master in the future, or releasing more often.

I thought about documenting the change but wasn't sure where, and since it's only on master, didn't think it would be much of an issue.

**Comment by LordMZTE** [comment]
Ah OK, that's fine. I got my config fixed after reading some of the code :D

**Comment by Toqozz** [comment]
Also check out #62 if you haven't already.
