### ISSUE TITLE
Can't render notification

### ISSUE THREAD

**Issue by liubog2008** [Toqozz/wired-notify#76]
version: 0.10.2

```
❯ RUST_BACKTRACE=full wired
A wired socket exists; taking ownership.  Existing wired processes will not receive CLI calls.
Notification bus name acquired.
Config reloaded.
[src/manager.rs:97] &notification = Notification: {
        id: 2,
        app_name: Wired,
        summary: Wired,
        body: Config was reloaded.,
        actions: {},
        app_image: false,
        hint_image: false,
        urgency: Low,
        percentage: None,
        time: 2022-06-21 10:41:28.024392670 +08:00,
        timeout: 5000
}
[src/manager.rs:97] &notification = Notification: {
        id: 3,
        app_name: notify-send,
        summary: Summary,
        body: A different body,
        actions: {},
        app_image: false,
        hint_image: false,
        urgency: Normal,
        percentage: None,
        time: 2022-06-21 10:41:42.253420686 +08:00,
        timeout: 4000
}
```

Notification can be displayed in log, but no notification window popup

**Comment by BeyondMagic** [comment]
Post the config so we can see what it is happening.

**Comment by liubog2008** [comment]
I use this config https://github.com/Toqozz/wired-notify/issues/63#issuecomment-1100855910

**Comment by liubog2008** [comment]
```
[src/manager.rs:97] &notification = Notification: {
        id: 4,
        app_name: xxx,
        summary: Approval,
        body: yyy,
        actions: {"default": "Activate"},
        app_image: true,
        hint_image: false,
        urgency: Normal,
        percentage: None,
        time: 2022-06-21 11:11:33.608194615 +08:00,
        timeout: 4000
}
```

I find the notification with actions like the above can be show, although the popup window is in the central of  the screen.

**Comment by BeyondMagic** [comment]
Well, it's not that hard to fix. I'll see later if I can update a few things on the Wiki later on, but the render part changed quite a bit:

See #62.

Modify the following lines for:

```rust
render_criteria: [AppImage],    -> render_criteria: [ And([AppImage]) ],
render_criteria: [Progress],    -> render_criteria: [ And([Progress]) ],
render_criteria: [HintImage],   -> render_criteria: [ And([HintImage]) ],
```

**Comment by liubog2008** [comment]
It worked after I delete `render_criteria`. I'll try to see the detail of all config fields. Thanks!

**Comment by BeyondMagic** [comment]
I wouldn't recommend just taking it out, since all of them are not supposed to be rendered at once. Please try to modify the lines I posted on the reply before yours later on.

**Comment by liubog2008** [comment]
> I wouldn't recommend just taking it out, since all of them are not supposed to be rendered at once. Please try to modify the lines I posted on the reply before yours later on.

Thanks, I'll try to adjust the config. Now the display is very strange, but at least, it's worked.

**Comment by liubog2008** [comment]
![image](https://user-images.githubusercontent.com/7920667/174746872-fa090252-2ab5-40d5-a5a4-ce9b3f9f87de.png)
