### ISSUE TITLE
[Question] Meaning of "Where to attach on this block"

### ISSUE THREAD

**Issue by TornaxO7** [Toqozz/wired-notify#78]
Hello, currently I'm reading [this table](https://github.com/Toqozz/wired-notify/wiki/Blocks#mandatory) and I'm wonderding what you mean with `Where to attach on this block` in the line with `hooks` in the first column. Could you please explain it a little bit more what it does?

**Comment by Toqozz** [comment]
Hey!  Please check out this section of the wiki: https://github.com/Toqozz/wired-notify/wiki/Blocks if you haven't already.

If you have questions still don't hesitate to ask!

**Comment by TornaxO7** [comment]
Hm... ok, I'll think about it. If I'll reopen this if I have any questions left. Thank you for your response!
