### ISSUE TITLE
Background Transparency

### ISSUE THREAD

**Issue by LordMZTE** [Toqozz/wired-notify#8]
A feature to make the background of notifications transparent would be great. I could configure picom to make the whole notification transparent, but ideally, there'd be a feature to make just the background transparent. This could be implemented as a config option in`NotificationBlock`.

**Comment by Toqozz** [comment]
This should be possible, and is a bug if it's not working.  I can't test right now, but will investigate more when I can.

**Comment by LordMZTE** [comment]
It is? I think it's undocumented then, since I couldn't find it on the wiki pages.

**Comment by LordMZTE** [comment]
Ah, I figured out that it's ARGB. Thanks for telling me this feature exists!

**Comment by Toqozz** [comment]
Looks like I overlooked actually showing how alpha is specified with hex colors.  I've changed it to use alpha in one of the `NotificationBlock` properties on the wiki page, hopefully this is enough.

Thanks for the issue regardless :).
