### ISSUE TITLE
Add cli command to pause/resume notifications

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#80]
I've run into the scenario where I'd like to instruct Wired to pause and resume notifications during specific periods of the day.

I already have the means to run other scripts on such occasions, and It'd be great to have a `wired pause` & `wired resume` feature on the CLI.

**Comment by Toqozz** [comment]
Cool, shouldn't be too difficult.

To be clear, do you want Wired to just effectively silence notifications while paused, so nothing shows?  As opposed to the other pause behaviour that currently exists where the notification will just sit there.

If the former, how should Wired respond when being resumed -- do we display all the notifications you "missed"? Could be hundreds!

**Comment by lukelex** [comment]
Either would work, but I'd prefer it not to show anything, as I can use `print_to_file` to retrieve what I've missed.

**Comment by Toqozz** [comment]
Available in master:

`wired --dnd on` / `wired --dnd off`.

**Comment by lukelex** [comment]
![image](https://user-images.githubusercontent.com/842850/182164441-509a9aab-d190-4202-a795-4ac960f8b714.png)
