### ISSUE TITLE
[Request] Pause notifications by default and unpause when cursor is moved or key pressed

### ISSUE THREAD

**Issue by 9IPOCJIABbI4** [Toqozz/wired-notify#85]
Mechanics of this type seems to be used on MacOS, maybe it will be simpler then your idle_threshold idea [here](https://github.com/Toqozz/wired-notify/issues/12#issuecomment-925525089.)

**Comment by Toqozz** [comment]
You *should* be able to emulate this behavior by just setting `idle_threshold` to `0`, or does this have some quirks I'm not thinking of ?

**Comment by 9IPOCJIABbI4** [comment]
You are right. It would be better to call request " automatically unpausing notifications on input". Setting idle_threshold to 0 will pause all notifications, but not unpause on input.

**Comment by Toqozz** [comment]
Actually I think I'm mistaken, because if you set `idle_threshold` to 0, then the notifications will re-pause as soon as you stop providing input.

**Comment by Toqozz** [comment]
I've added 2 new config options that are available on master branch:

`notifications_spawn_paused` and `unpause_on_input`.

Setting both of these to true should provide the desired behavior, feel free to re-open and let me know if it doesn't or if anything needs to be changed.

```rust
    // Wired will pause notifications if you are idle (no mouse or keyboard input) for longer than
    // `idle_threshold` seconds.
    // Note that notifications will not be automatically unpaused on wake, and will need to be manually
    // cleared, unless `unpause_on_input` is set to true.
    // Also note that no distinction is made between manually paused and idle paused notifications.
    // If `idle_threshold` is not specified, the behavior will be disabled entirely.
    //idle_threshold: 3600,

    // Notifications will spawn paused, and have to be manually unpaused or cleared by the user,
    // unless `unpause_on_input` is also set.
    //notifications_spawn_paused: false,

    // Unpause notifications when we receive any input after being idle for longer than 1 second.
    // Note that no distinction is made between manually paused notifications and idle paused/spawned notifications.
    //unpause_on_input: false,
```
