### ISSUE TITLE
Trigger action AND close notification in one click

### ISSUE THREAD

**Issue by LordMZTE** [Toqozz/wired-notify#9]
Is it possible to configure my keybinds with wired like this:
- left click: trigger action and close
- right click: close notification
- middle click: close all

Currently, I use this as my shortcut config:
```ron
shortcuts: ShortcutsConfig (
    notification_action1: 1,
    notification_close: 2,
    notification_closeall: 3,
)
```

This almost does it, but it doesn't close the notification when I left click it, but only triggers the action. Is it possible to configure this how I want it? If not, it would be great if a feature like this could be added!

**Comment by LordMZTE** [comment]
I would be happy to contribute this if we figure out how to implement this! 😄

**Comment by Toqozz** [comment]
Currently this is not possible -- 1 shortcut corresponds to 1 action, and there's no "fallthrough" behavior like you're describing.

This sounds like a good idea but I'm not quite sure how it should work.  How should we specify "if there is an action, do it, and then close" and also another use case may be: "if there is an action, do it, otherwise close".

I'd like to not break users configs if possible, but it seems tricky with the current the given implementation.

Two solutions I can think of:
- A base config option: `action_closes_notification` or similar, which closes the notification when any action is triggered.  This seems a bit inflexible.  I don't think I really like it.
- Separate actions which provide combined functionality, i.e. `notification_action1_and_close`.  This feels pretty clunky, but at least it's easy to understand, and from the user side you don't really see any of this complexity.  Internally this should only be 1 extra shortcut.

Alternatively, we rework how shortcuts work, but honestly I have no idea what that looks like.

Thoughts?

**Comment by LordMZTE** [comment]
Hey, I think your proposed solutions are a possibility, but I agree that theyre a little clunky. If we had to choose one of those, I think I would also prefer the second solution. But, although I'm not sure this is possible to do in RON, something like this would be great:
```ron
shortcuts: ShortcutsConfig (
    // support old format
    notification_closeall: 3,

    // new format; actions will be executed sequentially
    1: [
        notification_action1,
        notification_close,
    ],
)
```

And if that isn't possible with the serializer, I think this should be possible, while still allowing the old format to be used instead, by deserializing into an enum with `#[serde(untagged)]`:
```ron
shortcuts: {
    3: notification_closeall,
    1: [
        notification_action1,
        notification_close,
    ],
},
```

Do you think this is a good solution?

**Comment by Toqozz** [comment]
Something like that was my third idea.  Ideally I wanted to support OR functionality if we did something breaking (trigger action OR close), but I don't think it's actually that useful for reasons similar to above, so I'm happy to not care about it.

Thanks for the info on `#[serde(untagged)]`, I wasn't familiar with that attribute.  Unfortunately I *think* it would still be a breaking change (please forgive my laziness on testing).  Here's how `ShortcutsConfig` currently looks:
```rust
#[derive(Debug, Deserialize)]
pub struct ShortcutsConfig {
    pub notification_interact: Option<u8>,
    pub notification_close: Option<u8>,
    pub notification_closeall: Option<u8>,
    pub notification_pause: Option<u8>,

    pub notification_action1: Option<u8>,
    pub notification_action2: Option<u8>,
    pub notification_action3: Option<u8>,
    pub notification_action4: Option<u8>,
}
```

`#[serde(untagged)]` implies using an enum, probably something like the following (correct me if you think something different):
```rust
struct OldShortcutsConfig {
    // same as ShortcutsConfig above ^
}

#[serde(untagged)]
pub enum ShortcutsConfig {
    Shortcuts(OldShortcutsConfig),
    AdvancedShortcuts(Vec<(u8, Vec<String>>),    // probably not string, idk, this is ugly
}
```

Which could be configured like so:
```rust
shortcuts: ShortcutsConfig (
    (
        notification_interact: 1,
        ...
    )
)

// or...

shortcuts: ShortcutsConfig (
    [
        (1, [notification_interact]),
    ]
)
```

Notice the added brackets.  We could probably get around this somehow but it would be a paint -- I'd rather just write a custom deserializer at that point.

---

Assuming we don't want a custom deserializer, for a solution that maintains backwards compatibility while supporting "advanced shortcuts", maybe this can work:
```rust
pub struct ShortcutsConfig {
    pub notification_interact: Option<u8>,
    pub notification_close: Option<u8>,
    pub notification_closeall: Option<u8>,
    pub notification_pause: Option<u8>,

    pub notification_action1: Option<u8>,
    pub notification_action2: Option<u8>,
    pub notification_action3: Option<u8>,
    pub notification_action4: Option<u8>,

    pub advanced_shortcuts: Option<Vec<(u8, Vec<String>)>>,   // again, not too keen on this being a string
}
```

```rust
shortcuts: ShortcutsConfig (
    notification_interact: 2,
    advanced_shortcuts: [
        (1, [notification_interact, notification_close]),
    ]
)
```

---

Personally I feel this is over-engineering at the moment.  I'm still partial to the initial solution I outlined (the second one), and then if more use cases pop up in the future, we can consider breaking the old shortcuts config and "doing it right", as opposed to doing something awkward now that we need to change later anyway.

If you're still interested in contributing for this, let me know and we can discuss implementation details.

The code that handles actions currently is not *super* good for supporting this, but I think it should be workable, even if not beautiful: https://github.com/Toqozz/wired-notify/blob/47d370d40df56e09a2b3c70ee50bd5562e7fc234/src/management/mod.rs#L254-L292

**Comment by LordMZTE** [comment]
You might be right, my suggestion may be a little overengineered. Also, I didn't plan on using a `String`. What I had in mind was something like this
```rust
#[derive(Deserialize)]
pub struct ShortcutsConfig {
    // ... old shortcuts here
    pub advanced_shortcuts: Option<Vec<(u8, ShortcutType)>>,
}

#[derive(Deserialize)]
// this renames the serialized version to be snake_case,
// so it should have the same name as it does currently.
#[serde(rename_all = "snake_case")]
pub enum ShortcutType {
    NotificationInteract,
    NotificationClose,
    NotificationCloseall,
    NotificationPause,

    NotificationAction1,
    NotificationAction2,
    NotificationAction3,
    NotificationAction4,
}
```

I am still very much interested in contributing! So, what solution should we go for?

**Comment by Toqozz** [comment]
Ahh, that makes more sense.  That would work decently and I'm definitely a fan of having a `ShortcutType` sometime in the future, but for now I think we just do the simple thing and create some new shortcuts, namely:
```rust
notification_action1_and_close: Option<u8>,
notification_action2_and_close: Option<u8>,
notification_action3_and_close: Option<u8>,
notification_action4_and_close: Option<u8>,
```

From there, I expect the only issue is finding the nicest way to execute the additional shortcuts.

Thanks for the discussion overall.  I have a much better idea on what I wouldwant from a shortcuts rework and how we could execute. :)

**Comment by LordMZTE** [comment]
Alright, I'll get to implementing this then!
