### ISSUE TITLE
idea: expose notification urgency/paused as RenderCriteria

### ISSUE THREAD

**Issue by jokeyrhyme** [Toqozz/wired-notify#91]
Howdie, thanks again for this project, it's working very well for me <3

I noticed that we can change the `border_color` based on notification urgency with these optional properties: https://github.com/Toqozz/wired-notify/wiki/NotificationBlock#optional-properties

But, there's no way to change (e.g.) `background_color` or `font` (or any other property, it seems) based on urgency

Providing `..._low`, `..._critical`, and `..._paused` variations of every other property seems like a lot of work/mess

It occurs to me that we could expose these as variations in [`render_criteria`](https://github.com/Toqozz/wired-notify/blob/397b13a9a7992ca0b0b2fa2f5a11e0db394a2d3d/src/rendering/layout.rs#L42-L54), and that would allow us to provide urgency-specific definitions of blocks

It might even mean we could deprecate `border_color_low`, etc, although this isn't strictly necessary, and they might be popular enough that it's worth keeping these for convenience?

**Comment by Toqozz** [comment]
Glad to hear it's working well :)

You're totally right about the deprecation of the block fields.  They're more convenient but not very scalable.  I've started deprecating some of them already.

I've added an `Urgency` render criteria:
```
render_criteria: [Urgency("low")],
```
