### ISSUE TITLE
Add icon and hints to log

### ISSUE THREAD

**Issue by lukelex** [Toqozz/wired-notify#95]
When displaying notifications in a notification center, it'd be nice to have both provided icons and hints to make them look as similar as possible to Wired's. 
 
This is how the entries looks today in the log:

```json
{
  "id":202,
  "tag":null,
  "app_name":"Spotify",
  "summary":"Bridges",
  "body":"Courage My Love - For Now",
  "actions":{},
  "percentage":null,
  "urgency":"Low",
  "time":1660654022,
  "timeout":3000
}
```

**Comment by Toqozz** [comment]
Hmm.  This may be fine for notifications which specify an image by path, but most of the time the notification client just sends some raw byte data to us.  I'm not sure if there's even a way to realistically support those images.

We can absolutely provide hints, will do.

**Comment by lukelex** [comment]
Would it be possible to store both the raw data ones and the "path'd" ones as base64 in the logs?

**Comment by Toqozz** [comment]
I don't think that would really help.  The shortest we can probably do is just passing the data as raw bytes/chars and the "string" would be crazy long.  The correct way to do this would probably be to write the data to `/tmp/wired/some_image.png` but this is pretty wasteful and a lot of effort for something that doesn't seem that important.

**Comment by Toqozz** [comment]
Images are infeasible for now.  Maybe if we support icon hints we can print those out.

Notification hint data gets translated into other fields, like `tag`, `note`, and `percentage`, which are already visible, so having the raw hint itself in there seems wasteful.
