### ISSUE TITLE
[BUG] Trailing white space in the notification body

### ISSUE THREAD

**Issue by faynopi** [Toqozz/wired-notify#98]
Version: `0.10.2` - `wired-git` from aur
OS: Arch Linux + dwm

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

# Expected Behavior
I think the trailing spaces should be removed before sending the notification.

# Current Behavior
![image](https://user-images.githubusercontent.com/72174296/186961668-772e4640-a898-4901-a407-2e5733d11ea3.png)
This is a Brave browser advertising with just an empty space in the body.
 
## Steps to Reproduce
![image](https://user-images.githubusercontent.com/72174296/186962929-ced5d14f-c0f8-459c-9456-80e4e6900551.png)
```sh
notify-send "test" "   "
notify-send "test" " "
```

**Comment by Toqozz** [comment]
I think I considered this at some point and decided it's a bug with the notification sender, but I'm happy to change my mind.

An alternative is changing the `Body` `RenderCriteria` to ignore whitespace in the criteria, but I don't see this being particularly useful.

I think just trimming notifications is the right idea.

**Comment by Toqozz** [comment]
Fixed in 0.10.3.
